changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot[bot]

  categories:
    - title: 🚀 Features
      labels:
        - feat

    - title: 🐛 Bug Fixes
      labels:
        - fix

    - title: 📦 Dependencies
      labels:
        - deps

    - title: 🧰 Maintenance
      labels:
        - chore
        - ci
        - refactor
        - docs
        - perf
        - test

    - title: Other Changes
      labels:
        - "*"
