services:
  routeros:
    image: evilfreelancer/docker-routeros:7.23.5
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm # omit on Apple Silicon (no KVM there; container uses QEMU emulation)
    ports:
      - "2222:22"
      - "2223:23"
      - "8728:8728"
      - "8729:8729"
      - "8291:8291"
    volumes:
      - ./docker-data/routeros_data:/data
    networks:
      - default
      - routeros_net

  routeros6:
    image: evilfreelancer/docker-routeros:6.49.21
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm # omit on Apple Silicon (no KVM there; container uses QEMU emulation)
    ports:
      - "8000:80"
      - "2232:22"
      - "2233:23"
      - "8738:8728"
      - "8739:8729"
      - "8391:8291"
    volumes:
      - ./docker-data/routeros6_data:/data
    networks:
      - default
      - routeros6_net

  # hotspot-client-test:
  #   image: alpine
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     - routeros6_net
  #     # - default # tambahkan ini supaya bisa akses internet untuk apk add
  #   command: sleep infinity

  mikhmon:
    image: trianwar/mikhmon:latest
    ports:
      - "8080:8080"
    volumes:
      - ./docker-data/mikhmon:/var/www/mikhmon

networks:
  routeros6_net:
    driver: bridge
  routeros_net:
    driver: bridge
