/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authedIndexRouteImport } from './routes/(authed)/index'
import { Route as authedAppRouteRouteImport } from './routes/(authed)/app/route'
import { Route as authedSettingsRouteImport } from './routes/(authed)/settings'
import { Route as authedUsersRouteImport } from './routes/(authed)/users'
import { Route as InstallIndexRouteImport } from './routes/install/index'
import { Route as authedAppIndexRouteImport } from './routes/(authed)/app/index'
import { Route as authedVoucherTemplatesIndexRouteImport } from './routes/(authed)/voucher-templates/index'
import { Route as authedVoucherTemplatesCreateRouteImport } from './routes/(authed)/voucher-templates/create'
import { Route as authedAppDhcpLeasesIndexRouteImport } from './routes/(authed)/app/dhcp-leases/index'
import { Route as authedAppLogHotspotRouteImport } from './routes/(authed)/app/log/hotspot'
import { Route as authedAppLogUserRouteImport } from './routes/(authed)/app/log/user'
import { Route as authedAppPppActivesRouteImport } from './routes/(authed)/app/ppp/actives'
import { Route as authedAppQuickPrintIndexRouteImport } from './routes/(authed)/app/quick-print/index'
import { Route as authedAppReportIndexRouteImport } from './routes/(authed)/app/report/index'
import { Route as authedVoucherTemplatesIdEditRouteImport } from './routes/(authed)/voucher-templates/$id.edit'
import { Route as authedAppHotspotActivesIndexRouteImport } from './routes/(authed)/app/hotspot/actives/index'
import { Route as authedAppHotspotCookiesIndexRouteImport } from './routes/(authed)/app/hotspot/cookies/index'
import { Route as authedAppHotspotHostsIndexRouteImport } from './routes/(authed)/app/hotspot/hosts/index'
import { Route as authedAppHotspotIpBindingsIndexRouteImport } from './routes/(authed)/app/hotspot/ip-bindings/index'
import { Route as authedAppHotspotProfilesIndexRouteImport } from './routes/(authed)/app/hotspot/profiles/index'
import { Route as authedAppHotspotUsersIndexRouteImport } from './routes/(authed)/app/hotspot/users/index'
import { Route as authedAppPrintTemplateIdIndexRouteImport } from './routes/(authed)/app/print/$templateId.index'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authedIndexRoute = authedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedAppRouteRoute = authedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSettingsRoute = authedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedUsersRoute = authedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authedRouteRoute,
} as any)
const InstallIndexRoute = InstallIndexRouteImport.update({
  id: '/install/',
  path: '/install/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedAppIndexRoute = authedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedVoucherTemplatesIndexRoute =
  authedVoucherTemplatesIndexRouteImport.update({
    id: '/voucher-templates/',
    path: '/voucher-templates/',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedVoucherTemplatesCreateRoute =
  authedVoucherTemplatesCreateRouteImport.update({
    id: '/voucher-templates/create',
    path: '/voucher-templates/create',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedAppDhcpLeasesIndexRoute =
  authedAppDhcpLeasesIndexRouteImport.update({
    id: '/dhcp-leases/',
    path: '/dhcp-leases/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppLogHotspotRoute = authedAppLogHotspotRouteImport.update({
  id: '/log/hotspot',
  path: '/log/hotspot',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedAppLogUserRoute = authedAppLogUserRouteImport.update({
  id: '/log/user',
  path: '/log/user',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedAppPppActivesRoute = authedAppPppActivesRouteImport.update({
  id: '/ppp/actives',
  path: '/ppp/actives',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedAppQuickPrintIndexRoute =
  authedAppQuickPrintIndexRouteImport.update({
    id: '/quick-print/',
    path: '/quick-print/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppReportIndexRoute = authedAppReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedVoucherTemplatesIdEditRoute =
  authedVoucherTemplatesIdEditRouteImport.update({
    id: '/voucher-templates/$id/edit',
    path: '/voucher-templates/$id/edit',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedAppHotspotActivesIndexRoute =
  authedAppHotspotActivesIndexRouteImport.update({
    id: '/hotspot/actives/',
    path: '/hotspot/actives/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppHotspotCookiesIndexRoute =
  authedAppHotspotCookiesIndexRouteImport.update({
    id: '/hotspot/cookies/',
    path: '/hotspot/cookies/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppHotspotHostsIndexRoute =
  authedAppHotspotHostsIndexRouteImport.update({
    id: '/hotspot/hosts/',
    path: '/hotspot/hosts/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppHotspotIpBindingsIndexRoute =
  authedAppHotspotIpBindingsIndexRouteImport.update({
    id: '/hotspot/ip-bindings/',
    path: '/hotspot/ip-bindings/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppHotspotProfilesIndexRoute =
  authedAppHotspotProfilesIndexRouteImport.update({
    id: '/hotspot/profiles/',
    path: '/hotspot/profiles/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppHotspotUsersIndexRoute =
  authedAppHotspotUsersIndexRouteImport.update({
    id: '/hotspot/users/',
    path: '/hotspot/users/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppPrintTemplateIdIndexRoute =
  authedAppPrintTemplateIdIndexRouteImport.update({
    id: '/print/$templateId/',
    path: '/print/$templateId/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/app': typeof authedAppRouteRouteWithChildren
  '/settings': typeof authedSettingsRoute
  '/users': typeof authedUsersRoute
  '/': typeof authedIndexRoute
  '/install/': typeof InstallIndexRoute
  '/voucher-templates/create': typeof authedVoucherTemplatesCreateRoute
  '/app/': typeof authedAppIndexRoute
  '/voucher-templates/': typeof authedVoucherTemplatesIndexRoute
  '/app/log/hotspot': typeof authedAppLogHotspotRoute
  '/app/log/user': typeof authedAppLogUserRoute
  '/app/ppp/actives': typeof authedAppPppActivesRoute
  '/voucher-templates/$id/edit': typeof authedVoucherTemplatesIdEditRoute
  '/app/dhcp-leases/': typeof authedAppDhcpLeasesIndexRoute
  '/app/quick-print/': typeof authedAppQuickPrintIndexRoute
  '/app/report/': typeof authedAppReportIndexRoute
  '/app/hotspot/actives/': typeof authedAppHotspotActivesIndexRoute
  '/app/hotspot/cookies/': typeof authedAppHotspotCookiesIndexRoute
  '/app/hotspot/hosts/': typeof authedAppHotspotHostsIndexRoute
  '/app/hotspot/ip-bindings/': typeof authedAppHotspotIpBindingsIndexRoute
  '/app/hotspot/profiles/': typeof authedAppHotspotProfilesIndexRoute
  '/app/hotspot/users/': typeof authedAppHotspotUsersIndexRoute
  '/app/print/$templateId/': typeof authedAppPrintTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof authedSettingsRoute
  '/users': typeof authedUsersRoute
  '/': typeof authedIndexRoute
  '/install': typeof InstallIndexRoute
  '/voucher-templates/create': typeof authedVoucherTemplatesCreateRoute
  '/app': typeof authedAppIndexRoute
  '/voucher-templates': typeof authedVoucherTemplatesIndexRoute
  '/app/log/hotspot': typeof authedAppLogHotspotRoute
  '/app/log/user': typeof authedAppLogUserRoute
  '/app/ppp/actives': typeof authedAppPppActivesRoute
  '/voucher-templates/$id/edit': typeof authedVoucherTemplatesIdEditRoute
  '/app/dhcp-leases': typeof authedAppDhcpLeasesIndexRoute
  '/app/quick-print': typeof authedAppQuickPrintIndexRoute
  '/app/report': typeof authedAppReportIndexRoute
  '/app/hotspot/actives': typeof authedAppHotspotActivesIndexRoute
  '/app/hotspot/cookies': typeof authedAppHotspotCookiesIndexRoute
  '/app/hotspot/hosts': typeof authedAppHotspotHostsIndexRoute
  '/app/hotspot/ip-bindings': typeof authedAppHotspotIpBindingsIndexRoute
  '/app/hotspot/profiles': typeof authedAppHotspotProfilesIndexRoute
  '/app/hotspot/users': typeof authedAppHotspotUsersIndexRoute
  '/app/print/$templateId': typeof authedAppPrintTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authed)': typeof authedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(authed)/app': typeof authedAppRouteRouteWithChildren
  '/(authed)/settings': typeof authedSettingsRoute
  '/(authed)/users': typeof authedUsersRoute
  '/(authed)/': typeof authedIndexRoute
  '/install/': typeof InstallIndexRoute
  '/(authed)/voucher-templates/create': typeof authedVoucherTemplatesCreateRoute
  '/(authed)/app/': typeof authedAppIndexRoute
  '/(authed)/voucher-templates/': typeof authedVoucherTemplatesIndexRoute
  '/(authed)/app/log/hotspot': typeof authedAppLogHotspotRoute
  '/(authed)/app/log/user': typeof authedAppLogUserRoute
  '/(authed)/app/ppp/actives': typeof authedAppPppActivesRoute
  '/(authed)/voucher-templates/$id/edit': typeof authedVoucherTemplatesIdEditRoute
  '/(authed)/app/dhcp-leases/': typeof authedAppDhcpLeasesIndexRoute
  '/(authed)/app/quick-print/': typeof authedAppQuickPrintIndexRoute
  '/(authed)/app/report/': typeof authedAppReportIndexRoute
  '/(authed)/app/hotspot/actives/': typeof authedAppHotspotActivesIndexRoute
  '/(authed)/app/hotspot/cookies/': typeof authedAppHotspotCookiesIndexRoute
  '/(authed)/app/hotspot/hosts/': typeof authedAppHotspotHostsIndexRoute
  '/(authed)/app/hotspot/ip-bindings/': typeof authedAppHotspotIpBindingsIndexRoute
  '/(authed)/app/hotspot/profiles/': typeof authedAppHotspotProfilesIndexRoute
  '/(authed)/app/hotspot/users/': typeof authedAppHotspotUsersIndexRoute
  '/(authed)/app/print/$templateId/': typeof authedAppPrintTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/app'
    | '/settings'
    | '/users'
    | '/'
    | '/install/'
    | '/voucher-templates/create'
    | '/app/'
    | '/voucher-templates/'
    | '/app/log/hotspot'
    | '/app/log/user'
    | '/app/ppp/actives'
    | '/voucher-templates/$id/edit'
    | '/app/dhcp-leases/'
    | '/app/quick-print/'
    | '/app/report/'
    | '/app/hotspot/actives/'
    | '/app/hotspot/cookies/'
    | '/app/hotspot/hosts/'
    | '/app/hotspot/ip-bindings/'
    | '/app/hotspot/profiles/'
    | '/app/hotspot/users/'
    | '/app/print/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/users'
    | '/'
    | '/install'
    | '/voucher-templates/create'
    | '/app'
    | '/voucher-templates'
    | '/app/log/hotspot'
    | '/app/log/user'
    | '/app/ppp/actives'
    | '/voucher-templates/$id/edit'
    | '/app/dhcp-leases'
    | '/app/quick-print'
    | '/app/report'
    | '/app/hotspot/actives'
    | '/app/hotspot/cookies'
    | '/app/hotspot/hosts'
    | '/app/hotspot/ip-bindings'
    | '/app/hotspot/profiles'
    | '/app/hotspot/users'
    | '/app/print/$templateId'
  id:
    | '__root__'
    | '/(authed)'
    | '/login'
    | '/(authed)/app'
    | '/(authed)/settings'
    | '/(authed)/users'
    | '/(authed)/'
    | '/install/'
    | '/(authed)/voucher-templates/create'
    | '/(authed)/app/'
    | '/(authed)/voucher-templates/'
    | '/(authed)/app/log/hotspot'
    | '/(authed)/app/log/user'
    | '/(authed)/app/ppp/actives'
    | '/(authed)/voucher-templates/$id/edit'
    | '/(authed)/app/dhcp-leases/'
    | '/(authed)/app/quick-print/'
    | '/(authed)/app/report/'
    | '/(authed)/app/hotspot/actives/'
    | '/(authed)/app/hotspot/cookies/'
    | '/(authed)/app/hotspot/hosts/'
    | '/(authed)/app/hotspot/ip-bindings/'
    | '/(authed)/app/hotspot/profiles/'
    | '/(authed)/app/hotspot/users/'
    | '/(authed)/app/print/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authedRouteRoute: typeof authedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  InstallIndexRoute: typeof InstallIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/': {
      id: '/(authed)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authedIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/app': {
      id: '/(authed)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof authedAppRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/settings': {
      id: '/(authed)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authedSettingsRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/users': {
      id: '/(authed)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof authedUsersRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/install/': {
      id: '/install/'
      path: '/install'
      fullPath: '/install/'
      preLoaderRoute: typeof InstallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/app/': {
      id: '/(authed)/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof authedAppIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/voucher-templates/': {
      id: '/(authed)/voucher-templates/'
      path: '/voucher-templates'
      fullPath: '/voucher-templates/'
      preLoaderRoute: typeof authedVoucherTemplatesIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/voucher-templates/create': {
      id: '/(authed)/voucher-templates/create'
      path: '/voucher-templates/create'
      fullPath: '/voucher-templates/create'
      preLoaderRoute: typeof authedVoucherTemplatesCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/app/dhcp-leases/': {
      id: '/(authed)/app/dhcp-leases/'
      path: '/dhcp-leases'
      fullPath: '/app/dhcp-leases/'
      preLoaderRoute: typeof authedAppDhcpLeasesIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/log/hotspot': {
      id: '/(authed)/app/log/hotspot'
      path: '/log/hotspot'
      fullPath: '/app/log/hotspot'
      preLoaderRoute: typeof authedAppLogHotspotRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/log/user': {
      id: '/(authed)/app/log/user'
      path: '/log/user'
      fullPath: '/app/log/user'
      preLoaderRoute: typeof authedAppLogUserRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/ppp/actives': {
      id: '/(authed)/app/ppp/actives'
      path: '/ppp/actives'
      fullPath: '/app/ppp/actives'
      preLoaderRoute: typeof authedAppPppActivesRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/quick-print/': {
      id: '/(authed)/app/quick-print/'
      path: '/quick-print'
      fullPath: '/app/quick-print/'
      preLoaderRoute: typeof authedAppQuickPrintIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/report/': {
      id: '/(authed)/app/report/'
      path: '/report'
      fullPath: '/app/report/'
      preLoaderRoute: typeof authedAppReportIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/voucher-templates/$id/edit': {
      id: '/(authed)/voucher-templates/$id/edit'
      path: '/voucher-templates/$id/edit'
      fullPath: '/voucher-templates/$id/edit'
      preLoaderRoute: typeof authedVoucherTemplatesIdEditRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/app/hotspot/actives/': {
      id: '/(authed)/app/hotspot/actives/'
      path: '/hotspot/actives'
      fullPath: '/app/hotspot/actives/'
      preLoaderRoute: typeof authedAppHotspotActivesIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/cookies/': {
      id: '/(authed)/app/hotspot/cookies/'
      path: '/hotspot/cookies'
      fullPath: '/app/hotspot/cookies/'
      preLoaderRoute: typeof authedAppHotspotCookiesIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/hosts/': {
      id: '/(authed)/app/hotspot/hosts/'
      path: '/hotspot/hosts'
      fullPath: '/app/hotspot/hosts/'
      preLoaderRoute: typeof authedAppHotspotHostsIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/ip-bindings/': {
      id: '/(authed)/app/hotspot/ip-bindings/'
      path: '/hotspot/ip-bindings'
      fullPath: '/app/hotspot/ip-bindings/'
      preLoaderRoute: typeof authedAppHotspotIpBindingsIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/profiles/': {
      id: '/(authed)/app/hotspot/profiles/'
      path: '/hotspot/profiles'
      fullPath: '/app/hotspot/profiles/'
      preLoaderRoute: typeof authedAppHotspotProfilesIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/users/': {
      id: '/(authed)/app/hotspot/users/'
      path: '/hotspot/users'
      fullPath: '/app/hotspot/users/'
      preLoaderRoute: typeof authedAppHotspotUsersIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/print/$templateId/': {
      id: '/(authed)/app/print/$templateId/'
      path: '/print/$templateId'
      fullPath: '/app/print/$templateId/'
      preLoaderRoute: typeof authedAppPrintTemplateIdIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
  }
}

interface authedAppRouteRouteChildren {
  authedAppIndexRoute: typeof authedAppIndexRoute
  authedAppLogHotspotRoute: typeof authedAppLogHotspotRoute
  authedAppLogUserRoute: typeof authedAppLogUserRoute
  authedAppPppActivesRoute: typeof authedAppPppActivesRoute
  authedAppDhcpLeasesIndexRoute: typeof authedAppDhcpLeasesIndexRoute
  authedAppQuickPrintIndexRoute: typeof authedAppQuickPrintIndexRoute
  authedAppReportIndexRoute: typeof authedAppReportIndexRoute
  authedAppHotspotActivesIndexRoute: typeof authedAppHotspotActivesIndexRoute
  authedAppHotspotCookiesIndexRoute: typeof authedAppHotspotCookiesIndexRoute
  authedAppHotspotHostsIndexRoute: typeof authedAppHotspotHostsIndexRoute
  authedAppHotspotIpBindingsIndexRoute: typeof authedAppHotspotIpBindingsIndexRoute
  authedAppHotspotProfilesIndexRoute: typeof authedAppHotspotProfilesIndexRoute
  authedAppHotspotUsersIndexRoute: typeof authedAppHotspotUsersIndexRoute
  authedAppPrintTemplateIdIndexRoute: typeof authedAppPrintTemplateIdIndexRoute
}

const authedAppRouteRouteChildren: authedAppRouteRouteChildren = {
  authedAppIndexRoute: authedAppIndexRoute,
  authedAppLogHotspotRoute: authedAppLogHotspotRoute,
  authedAppLogUserRoute: authedAppLogUserRoute,
  authedAppPppActivesRoute: authedAppPppActivesRoute,
  authedAppDhcpLeasesIndexRoute: authedAppDhcpLeasesIndexRoute,
  authedAppQuickPrintIndexRoute: authedAppQuickPrintIndexRoute,
  authedAppReportIndexRoute: authedAppReportIndexRoute,
  authedAppHotspotActivesIndexRoute: authedAppHotspotActivesIndexRoute,
  authedAppHotspotCookiesIndexRoute: authedAppHotspotCookiesIndexRoute,
  authedAppHotspotHostsIndexRoute: authedAppHotspotHostsIndexRoute,
  authedAppHotspotIpBindingsIndexRoute: authedAppHotspotIpBindingsIndexRoute,
  authedAppHotspotProfilesIndexRoute: authedAppHotspotProfilesIndexRoute,
  authedAppHotspotUsersIndexRoute: authedAppHotspotUsersIndexRoute,
  authedAppPrintTemplateIdIndexRoute: authedAppPrintTemplateIdIndexRoute,
}

const authedAppRouteRouteWithChildren = authedAppRouteRoute._addFileChildren(
  authedAppRouteRouteChildren,
)

interface authedRouteRouteChildren {
  authedAppRouteRoute: typeof authedAppRouteRouteWithChildren
  authedSettingsRoute: typeof authedSettingsRoute
  authedUsersRoute: typeof authedUsersRoute
  authedIndexRoute: typeof authedIndexRoute
  authedVoucherTemplatesCreateRoute: typeof authedVoucherTemplatesCreateRoute
  authedVoucherTemplatesIndexRoute: typeof authedVoucherTemplatesIndexRoute
  authedVoucherTemplatesIdEditRoute: typeof authedVoucherTemplatesIdEditRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedAppRouteRoute: authedAppRouteRouteWithChildren,
  authedSettingsRoute: authedSettingsRoute,
  authedUsersRoute: authedUsersRoute,
  authedIndexRoute: authedIndexRoute,
  authedVoucherTemplatesCreateRoute: authedVoucherTemplatesCreateRoute,
  authedVoucherTemplatesIndexRoute: authedVoucherTemplatesIndexRoute,
  authedVoucherTemplatesIdEditRoute: authedVoucherTemplatesIdEditRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authedRouteRoute: authedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  InstallIndexRoute: InstallIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
