/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authedRouteRouteImport } from './routes/(authed)/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authedIndexRouteImport } from './routes/(authed)/index'
import { Route as authedAppRouteRouteImport } from './routes/(authed)/app/route'
import { Route as authedSettingsRouteImport } from './routes/(authed)/settings'
import { Route as authedUsersRouteImport } from './routes/(authed)/users'
import { Route as InstallIndexRouteImport } from './routes/install/index'
import { Route as authedAppIndexRouteImport } from './routes/(authed)/app/index'
import { Route as authedVoucherTemplatesIndexRouteImport } from './routes/(authed)/voucher-templates/index'
import { Route as authedVoucherTemplatesCreateRouteImport } from './routes/(authed)/voucher-templates/create'
import { Route as authedAppDhcpLeasesIndexRouteImport } from './routes/(authed)/app/dhcp-leases/index'
import { Route as authedAppHotspotActivesRouteImport } from './routes/(authed)/app/hotspot/actives'
import { Route as authedAppHotspotHostsRouteImport } from './routes/(authed)/app/hotspot/hosts'
import { Route as authedAppLogIndexRouteImport } from './routes/(authed)/app/log/index'
import { Route as authedAppQuickPrintIndexRouteImport } from './routes/(authed)/app/quick-print/index'
import { Route as authedVoucherTemplatesIdEditRouteImport } from './routes/(authed)/voucher-templates/$id.edit'
import { Route as authedAppHotspotProfilesIndexRouteImport } from './routes/(authed)/app/hotspot/profiles/index'
import { Route as authedAppHotspotUsersIndexRouteImport } from './routes/(authed)/app/hotspot/users/index'
import { Route as authedAppPrintTemplateIdIndexRouteImport } from './routes/(authed)/app/print/$templateId.index'

const authedRouteRoute = authedRouteRouteImport.update({
  id: '/(authed)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authedIndexRoute = authedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedAppRouteRoute = authedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedSettingsRoute = authedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => authedRouteRoute,
} as any)
const authedUsersRoute = authedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => authedRouteRoute,
} as any)
const InstallIndexRoute = InstallIndexRouteImport.update({
  id: '/install/',
  path: '/install/',
  getParentRoute: () => rootRouteImport,
} as any)
const authedAppIndexRoute = authedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedVoucherTemplatesIndexRoute =
  authedVoucherTemplatesIndexRouteImport.update({
    id: '/voucher-templates/',
    path: '/voucher-templates/',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedVoucherTemplatesCreateRoute =
  authedVoucherTemplatesCreateRouteImport.update({
    id: '/voucher-templates/create',
    path: '/voucher-templates/create',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedAppDhcpLeasesIndexRoute =
  authedAppDhcpLeasesIndexRouteImport.update({
    id: '/dhcp-leases/',
    path: '/dhcp-leases/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppHotspotActivesRoute = authedAppHotspotActivesRouteImport.update({
  id: '/hotspot/actives',
  path: '/hotspot/actives',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedAppHotspotHostsRoute = authedAppHotspotHostsRouteImport.update({
  id: '/hotspot/hosts',
  path: '/hotspot/hosts',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedAppLogIndexRoute = authedAppLogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => authedAppRouteRoute,
} as any)
const authedAppQuickPrintIndexRoute =
  authedAppQuickPrintIndexRouteImport.update({
    id: '/quick-print/',
    path: '/quick-print/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedVoucherTemplatesIdEditRoute =
  authedVoucherTemplatesIdEditRouteImport.update({
    id: '/voucher-templates/$id/edit',
    path: '/voucher-templates/$id/edit',
    getParentRoute: () => authedRouteRoute,
  } as any)
const authedAppHotspotProfilesIndexRoute =
  authedAppHotspotProfilesIndexRouteImport.update({
    id: '/hotspot/profiles/',
    path: '/hotspot/profiles/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppHotspotUsersIndexRoute =
  authedAppHotspotUsersIndexRouteImport.update({
    id: '/hotspot/users/',
    path: '/hotspot/users/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)
const authedAppPrintTemplateIdIndexRoute =
  authedAppPrintTemplateIdIndexRouteImport.update({
    id: '/print/$templateId/',
    path: '/print/$templateId/',
    getParentRoute: () => authedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/app': typeof authedAppRouteRouteWithChildren
  '/settings': typeof authedSettingsRoute
  '/users': typeof authedUsersRoute
  '/': typeof authedIndexRoute
  '/install/': typeof InstallIndexRoute
  '/voucher-templates/create': typeof authedVoucherTemplatesCreateRoute
  '/app/': typeof authedAppIndexRoute
  '/voucher-templates/': typeof authedVoucherTemplatesIndexRoute
  '/app/hotspot/actives': typeof authedAppHotspotActivesRoute
  '/app/hotspot/hosts': typeof authedAppHotspotHostsRoute
  '/voucher-templates/$id/edit': typeof authedVoucherTemplatesIdEditRoute
  '/app/dhcp-leases/': typeof authedAppDhcpLeasesIndexRoute
  '/app/log/': typeof authedAppLogIndexRoute
  '/app/quick-print/': typeof authedAppQuickPrintIndexRoute
  '/app/hotspot/profiles/': typeof authedAppHotspotProfilesIndexRoute
  '/app/hotspot/users/': typeof authedAppHotspotUsersIndexRoute
  '/app/print/$templateId/': typeof authedAppPrintTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof authedSettingsRoute
  '/users': typeof authedUsersRoute
  '/': typeof authedIndexRoute
  '/install': typeof InstallIndexRoute
  '/voucher-templates/create': typeof authedVoucherTemplatesCreateRoute
  '/app': typeof authedAppIndexRoute
  '/voucher-templates': typeof authedVoucherTemplatesIndexRoute
  '/app/hotspot/actives': typeof authedAppHotspotActivesRoute
  '/app/hotspot/hosts': typeof authedAppHotspotHostsRoute
  '/voucher-templates/$id/edit': typeof authedVoucherTemplatesIdEditRoute
  '/app/dhcp-leases': typeof authedAppDhcpLeasesIndexRoute
  '/app/log': typeof authedAppLogIndexRoute
  '/app/quick-print': typeof authedAppQuickPrintIndexRoute
  '/app/hotspot/profiles': typeof authedAppHotspotProfilesIndexRoute
  '/app/hotspot/users': typeof authedAppHotspotUsersIndexRoute
  '/app/print/$templateId': typeof authedAppPrintTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(authed)': typeof authedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(authed)/app': typeof authedAppRouteRouteWithChildren
  '/(authed)/settings': typeof authedSettingsRoute
  '/(authed)/users': typeof authedUsersRoute
  '/(authed)/': typeof authedIndexRoute
  '/install/': typeof InstallIndexRoute
  '/(authed)/voucher-templates/create': typeof authedVoucherTemplatesCreateRoute
  '/(authed)/app/': typeof authedAppIndexRoute
  '/(authed)/voucher-templates/': typeof authedVoucherTemplatesIndexRoute
  '/(authed)/app/hotspot/actives': typeof authedAppHotspotActivesRoute
  '/(authed)/app/hotspot/hosts': typeof authedAppHotspotHostsRoute
  '/(authed)/voucher-templates/$id/edit': typeof authedVoucherTemplatesIdEditRoute
  '/(authed)/app/dhcp-leases/': typeof authedAppDhcpLeasesIndexRoute
  '/(authed)/app/log/': typeof authedAppLogIndexRoute
  '/(authed)/app/quick-print/': typeof authedAppQuickPrintIndexRoute
  '/(authed)/app/hotspot/profiles/': typeof authedAppHotspotProfilesIndexRoute
  '/(authed)/app/hotspot/users/': typeof authedAppHotspotUsersIndexRoute
  '/(authed)/app/print/$templateId/': typeof authedAppPrintTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/app'
    | '/settings'
    | '/users'
    | '/'
    | '/install/'
    | '/voucher-templates/create'
    | '/app/'
    | '/voucher-templates/'
    | '/app/hotspot/actives'
    | '/app/hotspot/hosts'
    | '/voucher-templates/$id/edit'
    | '/app/dhcp-leases/'
    | '/app/log/'
    | '/app/quick-print/'
    | '/app/hotspot/profiles/'
    | '/app/hotspot/users/'
    | '/app/print/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/users'
    | '/'
    | '/install'
    | '/voucher-templates/create'
    | '/app'
    | '/voucher-templates'
    | '/app/hotspot/actives'
    | '/app/hotspot/hosts'
    | '/voucher-templates/$id/edit'
    | '/app/dhcp-leases'
    | '/app/log'
    | '/app/quick-print'
    | '/app/hotspot/profiles'
    | '/app/hotspot/users'
    | '/app/print/$templateId'
  id:
    | '__root__'
    | '/(authed)'
    | '/login'
    | '/(authed)/app'
    | '/(authed)/settings'
    | '/(authed)/users'
    | '/(authed)/'
    | '/install/'
    | '/(authed)/voucher-templates/create'
    | '/(authed)/app/'
    | '/(authed)/voucher-templates/'
    | '/(authed)/app/hotspot/actives'
    | '/(authed)/app/hotspot/hosts'
    | '/(authed)/voucher-templates/$id/edit'
    | '/(authed)/app/dhcp-leases/'
    | '/(authed)/app/log/'
    | '/(authed)/app/quick-print/'
    | '/(authed)/app/hotspot/profiles/'
    | '/(authed)/app/hotspot/users/'
    | '/(authed)/app/print/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authedRouteRoute: typeof authedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  InstallIndexRoute: typeof InstallIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authed)': {
      id: '/(authed)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/': {
      id: '/(authed)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authedIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/app': {
      id: '/(authed)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof authedAppRouteRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/settings': {
      id: '/(authed)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof authedSettingsRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/users': {
      id: '/(authed)/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof authedUsersRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/install/': {
      id: '/install/'
      path: '/install'
      fullPath: '/install/'
      preLoaderRoute: typeof InstallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authed)/app/': {
      id: '/(authed)/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof authedAppIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/voucher-templates/': {
      id: '/(authed)/voucher-templates/'
      path: '/voucher-templates'
      fullPath: '/voucher-templates/'
      preLoaderRoute: typeof authedVoucherTemplatesIndexRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/voucher-templates/create': {
      id: '/(authed)/voucher-templates/create'
      path: '/voucher-templates/create'
      fullPath: '/voucher-templates/create'
      preLoaderRoute: typeof authedVoucherTemplatesCreateRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/app/dhcp-leases/': {
      id: '/(authed)/app/dhcp-leases/'
      path: '/dhcp-leases'
      fullPath: '/app/dhcp-leases/'
      preLoaderRoute: typeof authedAppDhcpLeasesIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/actives': {
      id: '/(authed)/app/hotspot/actives'
      path: '/hotspot/actives'
      fullPath: '/app/hotspot/actives'
      preLoaderRoute: typeof authedAppHotspotActivesRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/hosts': {
      id: '/(authed)/app/hotspot/hosts'
      path: '/hotspot/hosts'
      fullPath: '/app/hotspot/hosts'
      preLoaderRoute: typeof authedAppHotspotHostsRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/log/': {
      id: '/(authed)/app/log/'
      path: '/log'
      fullPath: '/app/log/'
      preLoaderRoute: typeof authedAppLogIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/quick-print/': {
      id: '/(authed)/app/quick-print/'
      path: '/quick-print'
      fullPath: '/app/quick-print/'
      preLoaderRoute: typeof authedAppQuickPrintIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/voucher-templates/$id/edit': {
      id: '/(authed)/voucher-templates/$id/edit'
      path: '/voucher-templates/$id/edit'
      fullPath: '/voucher-templates/$id/edit'
      preLoaderRoute: typeof authedVoucherTemplatesIdEditRouteImport
      parentRoute: typeof authedRouteRoute
    }
    '/(authed)/app/hotspot/profiles/': {
      id: '/(authed)/app/hotspot/profiles/'
      path: '/hotspot/profiles'
      fullPath: '/app/hotspot/profiles/'
      preLoaderRoute: typeof authedAppHotspotProfilesIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/hotspot/users/': {
      id: '/(authed)/app/hotspot/users/'
      path: '/hotspot/users'
      fullPath: '/app/hotspot/users/'
      preLoaderRoute: typeof authedAppHotspotUsersIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
    '/(authed)/app/print/$templateId/': {
      id: '/(authed)/app/print/$templateId/'
      path: '/print/$templateId'
      fullPath: '/app/print/$templateId/'
      preLoaderRoute: typeof authedAppPrintTemplateIdIndexRouteImport
      parentRoute: typeof authedAppRouteRoute
    }
  }
}

interface authedAppRouteRouteChildren {
  authedAppIndexRoute: typeof authedAppIndexRoute
  authedAppHotspotActivesRoute: typeof authedAppHotspotActivesRoute
  authedAppHotspotHostsRoute: typeof authedAppHotspotHostsRoute
  authedAppDhcpLeasesIndexRoute: typeof authedAppDhcpLeasesIndexRoute
  authedAppLogIndexRoute: typeof authedAppLogIndexRoute
  authedAppQuickPrintIndexRoute: typeof authedAppQuickPrintIndexRoute
  authedAppHotspotProfilesIndexRoute: typeof authedAppHotspotProfilesIndexRoute
  authedAppHotspotUsersIndexRoute: typeof authedAppHotspotUsersIndexRoute
  authedAppPrintTemplateIdIndexRoute: typeof authedAppPrintTemplateIdIndexRoute
}

const authedAppRouteRouteChildren: authedAppRouteRouteChildren = {
  authedAppIndexRoute: authedAppIndexRoute,
  authedAppHotspotActivesRoute: authedAppHotspotActivesRoute,
  authedAppHotspotHostsRoute: authedAppHotspotHostsRoute,
  authedAppDhcpLeasesIndexRoute: authedAppDhcpLeasesIndexRoute,
  authedAppLogIndexRoute: authedAppLogIndexRoute,
  authedAppQuickPrintIndexRoute: authedAppQuickPrintIndexRoute,
  authedAppHotspotProfilesIndexRoute: authedAppHotspotProfilesIndexRoute,
  authedAppHotspotUsersIndexRoute: authedAppHotspotUsersIndexRoute,
  authedAppPrintTemplateIdIndexRoute: authedAppPrintTemplateIdIndexRoute,
}

const authedAppRouteRouteWithChildren = authedAppRouteRoute._addFileChildren(
  authedAppRouteRouteChildren,
)

interface authedRouteRouteChildren {
  authedAppRouteRoute: typeof authedAppRouteRouteWithChildren
  authedSettingsRoute: typeof authedSettingsRoute
  authedUsersRoute: typeof authedUsersRoute
  authedIndexRoute: typeof authedIndexRoute
  authedVoucherTemplatesCreateRoute: typeof authedVoucherTemplatesCreateRoute
  authedVoucherTemplatesIndexRoute: typeof authedVoucherTemplatesIndexRoute
  authedVoucherTemplatesIdEditRoute: typeof authedVoucherTemplatesIdEditRoute
}

const authedRouteRouteChildren: authedRouteRouteChildren = {
  authedAppRouteRoute: authedAppRouteRouteWithChildren,
  authedSettingsRoute: authedSettingsRoute,
  authedUsersRoute: authedUsersRoute,
  authedIndexRoute: authedIndexRoute,
  authedVoucherTemplatesCreateRoute: authedVoucherTemplatesCreateRoute,
  authedVoucherTemplatesIndexRoute: authedVoucherTemplatesIndexRoute,
  authedVoucherTemplatesIdEditRoute: authedVoucherTemplatesIdEditRoute,
}

const authedRouteRouteWithChildren = authedRouteRoute._addFileChildren(
  authedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authedRouteRoute: authedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  InstallIndexRoute: InstallIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
