name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title (Conventional Commits)
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716
          types: |
            breaking
            feat
            fix
            refactor
            chore
            test
            ci
          requireScope: false
